[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 5175
  port = 8888
  autoLaunch = false
  framework = "#custom"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
